# Using custom layouts (no remote_theme)
logo: /assets/images/logo.svg

title: ZAKARIA IZOUAOUEN
subtitle: PhD Researcher in Artificial Intelligence & Immersive Technologies
name: Zakaria Izouaouen

description: >
  Research and teaching in Artificial Intelligence, Machine Learning,
  and Immersive Technologies (VR/AR/MR). Focus on intelligent and secure systems,
  data-driven modeling, and educational innovation.

locale: en-US
timezone: Africa/Casablanca

author:
  name: Zakaria Izouaouen
  bio: >
    PhD Researcher in Artificial Intelligence and Immersive Technologies (VR/AR/MR).
    Specialized in intelligent systems, machine learning, data science,
    and secure system processing.
  location: Morocco
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/zkrzn
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://linkedin.com/in/zakaria-izouaouen

include:
  - _pages

masthead_links:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-feed
